# ---------------------------------------------------------------------------
# Multi-right-hand-side solves and refinement.
#
# A right-hand side of another element type (a `Complex{TG}`, a `ForwardDiff.Dual`, a matrix)
# decomposes into `m` channels of the solve type `TG` (see `_channels` in numeric.jl).  The
# single-vector `_ldiv_same!` streams every block's `L` / `Gᵀ` (dense) or `L`/`U` (LU) once
# per channel; here one block-major pass over the block triangular form solves all `m`
# channels together, each block's kernel applied to channel groups of 4 / 2 / 1, so a
# multiplier or `Gᵀ` element loaded once serves four channels.  Measured 1.2–2.4× per
# right-hand side (`benchmark/multirhs.jl`); allocation-free after the first call for a
# given `m` (a complex shift on a real reduction copies each channel of a large block through
# the block work area for the per-plane fallback).  `m == 1`, the scalar and LU block kernels
# and the off-diagonal scatter are bit-identical to the single-vector path; the dense (LHL)
# blocks differ only at rounding (the back substitution's reductions carry `4·C`
# accumulators), so a whole solve is bitwise equal to the per-column solve on a
# block-diagonal matrix and, with dense diagonal blocks, only to rounding.
#
# The channels are the columns of an `n × m` scratch in the permuted (block) order; a block
# `k` owns rows `R[k]:R[k+1]-1` of every channel, at `P[xo + (c-1)·n + i]` where `xo` is the
# channel group's base.  The fused kernels are generated by `@nexprs` for `C ∈ (1, 2, 4)`.
# ---------------------------------------------------------------------------

using Base.Cartesian: @nexprs

# ---- Fused small-block kernels.  `Y` (the `TG` work area) holds channel `c` at
# `Y[(c-1)*b + i]`; `vs` is the real reduction (factors / `L` multipliers / balancing),
# `gs` the `TG` shift (`Gᵀ`, pivot reciprocals).  Same algorithm as `_sb_linv!` / `_sb_hess!`
# / `_sb_l!`, the channel loop unrolled inside every step.
for C in (1, 2, 4)
    @eval begin
        @inline function _sbm_linv!(Y::Vector{TG}, vs::Vector{T}, o::Int, b::Int, ::Val{$C}) where {T, TG}
            G = max(b - 2, 0) >> 2
            @inbounds begin
                @nexprs $C c -> (yo_c = (c - 1) * b)
                for g in 1:G
                    k = 4g - 3
                    c1 = o + (k - 1) * b
                    c2 = c1 + b
                    c3 = c2 + b
                    c4 = c3 + b
                    l21 = vs[c1 + k + 2]
                    l31 = vs[c1 + k + 3]
                    l32 = vs[c2 + k + 3]
                    l41 = vs[c1 + k + 4]
                    l42 = vs[c2 + k + 4]
                    l43 = vs[c3 + k + 4]
                    @nexprs $C c -> begin
                        x1_c = Y[yo_c + k + 1]
                        x2_c = muladd(-l21, x1_c, Y[yo_c + k + 2])
                        Y[yo_c + k + 2] = x2_c
                        x3_c = muladd(-l32, x2_c, muladd(-l31, x1_c, Y[yo_c + k + 3]))
                        Y[yo_c + k + 3] = x3_c
                        x4_c = muladd(-l43, x3_c, muladd(-l42, x2_c, muladd(-l41, x1_c, Y[yo_c + k + 4])))
                        Y[yo_c + k + 4] = x4_c
                    end
                    @simd ivdep for i in (k + 5):b
                        m1 = vs[c1 + i]
                        m2 = vs[c2 + i]
                        m3 = vs[c3 + i]
                        m4 = vs[c4 + i]
                        @nexprs $C c -> begin
                            Y[yo_c + i] = muladd(-m4, x4_c, muladd(-m3, x3_c, muladd(-m2, x2_c, muladd(-m1, x1_c, Y[yo_c + i]))))
                        end
                    end
                end
                for k in (4G + 1):(b - 2)
                    ck = o + (k - 1) * b
                    @nexprs $C c -> (xk_c = Y[yo_c + k + 1])
                    @simd ivdep for i in (k + 2):b
                        l = vs[ck + i]
                        @nexprs $C c -> (Y[yo_c + i] = muladd(-l, xk_c, Y[yo_c + i]))
                    end
                end
            end
            return nothing
        end

        @inline function _sbm_l!(Y::Vector{TG}, vs::Vector{T}, o::Int, b::Int, ::Val{$C}) where {T, TG}
            G = max(b - 2, 0) >> 2
            @inbounds begin
                @nexprs $C c -> (yo_c = (c - 1) * b)
                for k in (b - 2):-1:(4G + 1)
                    ck = o + (k - 1) * b
                    @nexprs $C c -> (xk_c = Y[yo_c + k + 1])
                    @simd ivdep for i in (k + 2):b
                        l = vs[ck + i]
                        @nexprs $C c -> (Y[yo_c + i] = muladd(l, xk_c, Y[yo_c + i]))
                    end
                end
                for g in G:-1:1
                    k = 4g - 3
                    c1 = o + (k - 1) * b
                    c2 = c1 + b
                    c3 = c2 + b
                    c4 = c3 + b
                    l21 = vs[c1 + k + 2]
                    l31 = vs[c1 + k + 3]
                    l32 = vs[c2 + k + 3]
                    l41 = vs[c1 + k + 4]
                    l42 = vs[c2 + k + 4]
                    l43 = vs[c3 + k + 4]
                    @nexprs $C c -> begin
                        x1_c = Y[yo_c + k + 1]
                        x2_c = Y[yo_c + k + 2]
                        x3_c = Y[yo_c + k + 3]
                        x4_c = Y[yo_c + k + 4]
                        Y[yo_c + k + 2] = muladd(l21, x1_c, x2_c)
                        Y[yo_c + k + 3] = muladd(l32, x2_c, muladd(l31, x1_c, x3_c))
                        Y[yo_c + k + 4] = muladd(l43, x3_c, muladd(l42, x2_c, muladd(l41, x1_c, x4_c)))
                    end
                    @simd ivdep for i in (k + 5):b
                        m1 = vs[c1 + i]
                        m2 = vs[c2 + i]
                        m3 = vs[c3 + i]
                        m4 = vs[c4 + i]
                        @nexprs $C c -> begin
                            Y[yo_c + i] = muladd(m4, x4_c, muladd(m3, x3_c, muladd(m2, x2_c, muladd(m1, x1_c, Y[yo_c + i]))))
                        end
                    end
                end
            end
            return nothing
        end

        @inline function _sbm_hess!(Y::Vector{TG}, gs::Vector{TG}, g0::Int, b::Int, sw::Vector{Bool}, so::Int, ::Val{$C}) where {TG}
            oGt = _sb_gGt(g0, b)
            ord = _sb_grd(g0, b)
            @inbounds begin
                @nexprs $C c -> (yo_c = (c - 1) * b)
                for k in 1:(b - 1)
                    s = sw[so + k]
                    gk = gs[oGt + k + k * b]
                    @nexprs $C c -> begin
                        a = Y[yo_c + k]
                        d = Y[yo_c + k + 1]
                        xk = ifelse(s, d, a)
                        Y[yo_c + k] = xk
                        Y[yo_c + k + 1] = muladd(-gk, xk, ifelse(s, a, d))
                    end
                end
                j = b
                @nexprs $C c -> (s1_c = zero(TG); s2_c = zero(TG); s3_c = zero(TG); s4_c = zero(TG))
                while j - 3 >= 1
                    g1 = oGt + (j - 2) * b
                    g2 = g1 - b
                    g3 = g2 - b
                    r0 = gs[ord + j]
                    r1 = gs[ord + j - 1]
                    r2 = gs[ord + j - 2]
                    r3 = gs[ord + j - 3]
                    a10 = gs[g1 + j]
                    a20 = gs[g2 + j]
                    a30 = gs[g3 + j]
                    a21 = gs[g2 + j - 1]
                    a31 = gs[g3 + j - 1]
                    a32 = gs[g3 + j - 2]
                    @nexprs $C c -> begin
                        xj_c = (Y[yo_c + j] - s1_c) * r0
                        Y[yo_c + j] = xj_c
                        s2_c = muladd(a10, xj_c, s2_c)
                        s3_c = muladd(a20, xj_c, s3_c)
                        s4_c = muladd(a30, xj_c, s4_c)
                        xj1_c = (Y[yo_c + j - 1] - s2_c) * r1
                        Y[yo_c + j - 1] = xj1_c
                        s3_c = muladd(a21, xj1_c, s3_c)
                        s4_c = muladd(a31, xj1_c, s4_c)
                        xj2_c = (Y[yo_c + j - 2] - s3_c) * r2
                        Y[yo_c + j - 2] = xj2_c
                        s4_c = muladd(a32, xj2_c, s4_c)
                        xj3_c = (Y[yo_c + j - 3] - s4_c) * r3
                        Y[yo_c + j - 3] = xj3_c
                    end
                    jn = j - 4
                    if jn - 3 >= 1
                        h0 = oGt + (jn - 1) * b
                        h1 = h0 - b
                        h2 = h1 - b
                        h3 = h2 - b
                        @nexprs $C c -> (t1_c = zero(TG); t2_c = zero(TG); t3_c = zero(TG); t4_c = zero(TG))
                        @simd for i in (j + 1):b
                            q0 = gs[h0 + i]
                            q1 = gs[h1 + i]
                            q2 = gs[h2 + i]
                            q3 = gs[h3 + i]
                            @nexprs $C c -> begin
                                xi_c = Y[yo_c + i]
                                t1_c = muladd(q0, xi_c, t1_c)
                                t2_c = muladd(q1, xi_c, t2_c)
                                t3_c = muladd(q2, xi_c, t3_c)
                                t4_c = muladd(q3, xi_c, t4_c)
                            end
                        end
                        @nexprs $C c -> begin
                            s1_c = muladd(gs[h0 + j - 3], xj3_c, muladd(gs[h0 + j - 2], xj2_c, muladd(gs[h0 + j - 1], xj1_c, muladd(gs[h0 + j], xj_c, t1_c))))
                            s2_c = muladd(gs[h1 + j - 3], xj3_c, muladd(gs[h1 + j - 2], xj2_c, muladd(gs[h1 + j - 1], xj1_c, muladd(gs[h1 + j], xj_c, t2_c))))
                            s3_c = muladd(gs[h2 + j - 3], xj3_c, muladd(gs[h2 + j - 2], xj2_c, muladd(gs[h2 + j - 1], xj1_c, muladd(gs[h2 + j], xj_c, t3_c))))
                            s4_c = muladd(gs[h3 + j - 3], xj3_c, muladd(gs[h3 + j - 2], xj2_c, muladd(gs[h3 + j - 1], xj1_c, muladd(gs[h3 + j], xj_c, t4_c))))
                        end
                    end
                    j = jn
                end
                while j >= 1
                    gj = oGt + (j - 1) * b
                    @nexprs $C c -> (s_c = zero(TG))
                    @simd for i in (j + 1):b
                        q = gs[gj + i]
                        @nexprs $C c -> (s_c = muladd(q, Y[yo_c + i], s_c))
                    end
                    r = gs[ord + j]
                    @nexprs $C c -> (Y[yo_c + j] = (Y[yo_c + j] - s_c) * r)
                    j -= 1
                end
            end
            return nothing
        end

        @inline function _sbm_solve_core!(
                vs::Vector{T}, o::Int, gs::Vector{TG}, g0::Int, b::Int, is::Vector{Int}, io::Int,
                sw::Vector{Bool}, so::Int, Y::Vector{TG}, P::Matrix{TG}, xo::Int, n::Int, ::Val{$C}
            ) where {T, TG}
            osc = _sb_osc(o, b)
            oisc = _sb_oisc(o, b)
            operm = _sb_operm(io, b)
            oiperm = _sb_oiperm(io, b)
            @inbounds begin
                @nexprs $C c -> (yo_c = (c - 1) * b; xo_c = xo + (c - 1) * n)
                for i in 1:b
                    p = is[operm + i]
                    sc = vs[oisc + p]
                    @nexprs $C c -> (Y[yo_c + i] = P[xo_c + p] * sc)
                end
                _sbm_linv!(Y, vs, o, b, Val($C))
                _sbm_hess!(Y, gs, g0, b, sw, so, Val($C))
                _sbm_l!(Y, vs, o, b, Val($C))
                for i in 1:b
                    ip = is[oiperm + i]
                    sc = vs[osc + i]
                    @nexprs $C c -> (P[xo_c + i] = Y[yo_c + ip] * sc)
                end
            end
            return nothing
        end
        function _sbm_solve!(
                vs::Vector{T}, o::Int, gs::Vector{TG}, g0::Int, b::Int, is::Vector{Int}, io::Int,
                sw::Vector{Bool}, so::Int, Y::Vector{TG}, P::Matrix{TG}, xo::Int, n::Int, ::Val{$C}
            ) where {T, TG}
            return _sbm_solve_core!(vs, o, gs, g0, b, is, io, sw, so, Y, P, xo, n, Val($C))
        end
        @inline function _sbm_solve!(
                vs::Vector{T}, o::Int, gs::Vector{TG}, g0::Int, ::Val{B}, is::Vector{Int}, io::Int,
                sw::Vector{Bool}, so::Int, Y::Vector{TG}, P::Matrix{TG}, xo::Int, n::Int, ::Val{$C}
            ) where {T, TG, B}
            return _sbm_solve_core!(vs, o, gs, g0, B, is, io, sw, so, Y, P, xo, n, Val($C))
        end
    end
end

@inline function _sbm_dispatch!(vs::Vector{T}, o::Int, gs::Vector{TG}, g0::Int, b::Int, args...) where {T, TG}
    b == 2 && return _sbm_solve!(vs, o, gs, g0, Val(2), args...)
    b == 3 && return _sbm_solve!(vs, o, gs, g0, Val(3), args...)
    b == 4 && return _sbm_solve!(vs, o, gs, g0, Val(4), args...)
    b == 5 && return _sbm_solve!(vs, o, gs, g0, Val(5), args...)
    b == 6 && return _sbm_solve!(vs, o, gs, g0, Val(6), args...)
    b == 7 && return _sbm_solve!(vs, o, gs, g0, Val(7), args...)
    b == 8 && return _sbm_solve!(vs, o, gs, g0, Val(8), args...)
    return _sbm_solve!(vs, o, gs, g0, b, args...)
end

# ---- Fused multi-plane solve for a large (LHLWorkspace) block, real reduction and real
# shift only (`TG <: Real`): the plain column-major `L` multipliers in `ws.factors` (its
# `fstore` parent) and the shift's `Gᵀ` / `rdiag` / `swap` in `LHLShift`, `C` planes at once
# (plane `c` at `Z[(c-1)*ps + i]`).  This sidesteps LHLFactorization's packed `Lp` layout.
for C in (1, 2, 4)
    @eval begin
        @inline function _bigm_zinv!(Z::Vector{T}, ps::Int, A::AbstractMatrix{T}, n::Int, ::Val{$C}) where {T}
            G = max(n - 2, 0) >> 2
            @inbounds begin
                @nexprs $C c -> (zo_c = (c - 1) * ps)
                for g in 1:G
                    k = 4g - 3
                    l21 = A[k + 2, k]
                    l31 = A[k + 3, k]
                    l32 = A[k + 3, k + 1]
                    l41 = A[k + 4, k]
                    l42 = A[k + 4, k + 1]
                    l43 = A[k + 4, k + 2]
                    @nexprs $C c -> begin
                        x1_c = Z[zo_c + k + 1]
                        x2_c = muladd(-l21, x1_c, Z[zo_c + k + 2])
                        Z[zo_c + k + 2] = x2_c
                        x3_c = muladd(-l32, x2_c, muladd(-l31, x1_c, Z[zo_c + k + 3]))
                        Z[zo_c + k + 3] = x3_c
                        x4_c = muladd(-l43, x3_c, muladd(-l42, x2_c, muladd(-l41, x1_c, Z[zo_c + k + 4])))
                        Z[zo_c + k + 4] = x4_c
                    end
                    @simd ivdep for i in (k + 5):n
                        m1 = A[i, k]
                        m2 = A[i, k + 1]
                        m3 = A[i, k + 2]
                        m4 = A[i, k + 3]
                        @nexprs $C c -> begin
                            Z[zo_c + i] = muladd(-m4, x4_c, muladd(-m3, x3_c, muladd(-m2, x2_c, muladd(-m1, x1_c, Z[zo_c + i]))))
                        end
                    end
                end
                for k in (4G + 1):(n - 2)
                    @nexprs $C c -> (xk_c = Z[zo_c + k + 1])
                    @simd ivdep for i in (k + 2):n
                        l = A[i, k]
                        @nexprs $C c -> (Z[zo_c + i] = muladd(-l, xk_c, Z[zo_c + i]))
                    end
                end
            end
            return nothing
        end

        @inline function _bigm_z!(Z::Vector{T}, ps::Int, A::AbstractMatrix{T}, n::Int, ::Val{$C}) where {T}
            G = max(n - 2, 0) >> 2
            @inbounds begin
                @nexprs $C c -> (zo_c = (c - 1) * ps)
                for k in (n - 2):-1:(4G + 1)
                    @nexprs $C c -> (xk_c = Z[zo_c + k + 1])
                    @simd ivdep for i in (k + 2):n
                        l = A[i, k]
                        @nexprs $C c -> (Z[zo_c + i] = muladd(l, xk_c, Z[zo_c + i]))
                    end
                end
                for g in G:-1:1
                    k = 4g - 3
                    l21 = A[k + 2, k]
                    l31 = A[k + 3, k]
                    l32 = A[k + 3, k + 1]
                    l41 = A[k + 4, k]
                    l42 = A[k + 4, k + 1]
                    l43 = A[k + 4, k + 2]
                    @nexprs $C c -> begin
                        x1_c = Z[zo_c + k + 1]
                        x2_c = Z[zo_c + k + 2]
                        x3_c = Z[zo_c + k + 3]
                        x4_c = Z[zo_c + k + 4]
                        Z[zo_c + k + 2] = muladd(l21, x1_c, x2_c)
                        Z[zo_c + k + 3] = muladd(l32, x2_c, muladd(l31, x1_c, x3_c))
                        Z[zo_c + k + 4] = muladd(l43, x3_c, muladd(l42, x2_c, muladd(l41, x1_c, x4_c)))
                    end
                    @simd ivdep for i in (k + 5):n
                        m1 = A[i, k]
                        m2 = A[i, k + 1]
                        m3 = A[i, k + 2]
                        m4 = A[i, k + 3]
                        @nexprs $C c -> begin
                            Z[zo_c + i] = muladd(m4, x4_c, muladd(m3, x3_c, muladd(m2, x2_c, muladd(m1, x1_c, Z[zo_c + i]))))
                        end
                    end
                end
            end
            return nothing
        end

        @inline function _bigm_hess!(Z::Vector{T}, ps::Int, Gt::Matrix{T}, rd::Vector{T}, sw::Vector{Bool}, n::Int, ::Val{$C}) where {T}
            @inbounds begin
                @nexprs $C c -> (zo_c = (c - 1) * ps)
                for k in 1:(n - 1)
                    s = sw[k]
                    g = Gt[k, k + 1]
                    @nexprs $C c -> begin
                        a = Z[zo_c + k]
                        d = Z[zo_c + k + 1]
                        xk = ifelse(s, d, a)
                        Z[zo_c + k] = xk
                        Z[zo_c + k + 1] = muladd(-g, xk, ifelse(s, a, d))
                    end
                end
                j = n
                @nexprs $C c -> (s1_c = zero(T); s2_c = zero(T); s3_c = zero(T); s4_c = zero(T))
                while j - 3 >= 1
                    r0 = rd[j]
                    r1 = rd[j - 1]
                    r2 = rd[j - 2]
                    r3 = rd[j - 3]
                    a10 = Gt[j, j - 1]
                    a20 = Gt[j, j - 2]
                    a30 = Gt[j, j - 3]
                    a21 = Gt[j - 1, j - 2]
                    a31 = Gt[j - 1, j - 3]
                    a32 = Gt[j - 2, j - 3]
                    @nexprs $C c -> begin
                        xj_c = (Z[zo_c + j] - s1_c) * r0
                        Z[zo_c + j] = xj_c
                        s2_c = muladd(a10, xj_c, s2_c)
                        s3_c = muladd(a20, xj_c, s3_c)
                        s4_c = muladd(a30, xj_c, s4_c)
                        xj1_c = (Z[zo_c + j - 1] - s2_c) * r1
                        Z[zo_c + j - 1] = xj1_c
                        s3_c = muladd(a21, xj1_c, s3_c)
                        s4_c = muladd(a31, xj1_c, s4_c)
                        xj2_c = (Z[zo_c + j - 2] - s3_c) * r2
                        Z[zo_c + j - 2] = xj2_c
                        s4_c = muladd(a32, xj2_c, s4_c)
                        xj3_c = (Z[zo_c + j - 3] - s4_c) * r3
                        Z[zo_c + j - 3] = xj3_c
                    end
                    jn = j - 4
                    if jn - 3 >= 1
                        @nexprs $C c -> (t1_c = zero(T); t2_c = zero(T); t3_c = zero(T); t4_c = zero(T))
                        @simd for i in (j + 1):n
                            q0 = Gt[i, jn]
                            q1 = Gt[i, jn - 1]
                            q2 = Gt[i, jn - 2]
                            q3 = Gt[i, jn - 3]
                            @nexprs $C c -> begin
                                xi_c = Z[zo_c + i]
                                t1_c = muladd(q0, xi_c, t1_c)
                                t2_c = muladd(q1, xi_c, t2_c)
                                t3_c = muladd(q2, xi_c, t3_c)
                                t4_c = muladd(q3, xi_c, t4_c)
                            end
                        end
                        @nexprs $C c -> begin
                            s1_c = muladd(Gt[j - 3, jn], xj3_c, muladd(Gt[j - 2, jn], xj2_c, muladd(Gt[j - 1, jn], xj1_c, muladd(Gt[j, jn], xj_c, t1_c))))
                            s2_c = muladd(Gt[j - 3, jn - 1], xj3_c, muladd(Gt[j - 2, jn - 1], xj2_c, muladd(Gt[j - 1, jn - 1], xj1_c, muladd(Gt[j, jn - 1], xj_c, t2_c))))
                            s3_c = muladd(Gt[j - 3, jn - 2], xj3_c, muladd(Gt[j - 2, jn - 2], xj2_c, muladd(Gt[j - 1, jn - 2], xj1_c, muladd(Gt[j, jn - 2], xj_c, t3_c))))
                            s4_c = muladd(Gt[j - 3, jn - 3], xj3_c, muladd(Gt[j - 2, jn - 3], xj2_c, muladd(Gt[j - 1, jn - 3], xj1_c, muladd(Gt[j, jn - 3], xj_c, t4_c))))
                        end
                    end
                    j = jn
                end
                while j >= 1
                    @nexprs $C c -> (s_c = zero(T))
                    @simd for i in (j + 1):n
                        q = Gt[i, j]
                        @nexprs $C c -> (s_c = muladd(q, Z[zo_c + i], s_c))
                    end
                    r = rd[j]
                    @nexprs $C c -> (Z[zo_c + j] = (Z[zo_c + j] - s_c) * r)
                    j -= 1
                end
            end
            return nothing
        end

        # C planes at once, real reduction and real shift.  `ws.factors` is a view into a
        # padded `fstore`; `parent(ws.factors)` gives the padded matrix, whose leading
        # `b` columns hold `L` in the annihilated positions — the same the single-vector
        # `applyZinv!`/`applyZ!` read.
        @inline function _bigm_solve!(sh::LHLShift{TG, TG}, ws::LHLWorkspace{T}, Z::Vector{TG}, P::Matrix{TG}, xo::Int, n::Int, ::Val{$C}) where {T <: Real, TG <: Real}
            b = ws.n
            A = ws.factors
            perm = ws.perm
            iperm = ws.iperm
            isc = ws.iscale
            d = ws.scale
            @inbounds begin
                @nexprs $C c -> (zo_c = (c - 1) * b; xo_c = xo + (c - 1) * n)
                for i in 1:b
                    p = perm[i]
                    s = isc[p]
                    @nexprs $C c -> (Z[zo_c + i] = P[xo_c + p] * s)
                end
                _bigm_zinv!(Z, b, A, b, Val($C))
                _bigm_hess!(Z, b, sh.Gt, sh.rdiag, sh.swap, b, Val($C))
                _bigm_z!(Z, b, A, b, Val($C))
                for i in 1:b
                    ip = iperm[i]
                    s = d[i]
                    @nexprs $C c -> (P[xo_c + i] = Z[zo_c + ip] * s)
                end
            end
            return nothing
        end
        # complex shift (planar Gᵀ) or complex reduction: LHLFactorization's per-channel solve,
        # each channel copied through the block work area `Z` — a view of a `Vector` reaches
        # `lhl_ldiv!` without heap-allocating, a linear-range view of a `Matrix` would not.
        @inline function _bigm_solve!(sh::LHLShift, ws::LHLWorkspace, Z::AbstractVector, P::Matrix, xo::Int, n::Int, ::Val{$C})
            b = ws.n
            zv = view(Z, 1:b)
            @inbounds for c in 1:$C
                o = xo + (c - 1) * n
                for i in 1:b
                    Z[i] = P[o + i]
                end
                lhl_ldiv!(zv, sh, ws)
                for i in 1:b
                    P[o + i] = Z[i]
                end
            end
            return nothing
        end

        # off-diagonal scatter of block k (permuted columns k1:k2) into earlier rows, C channels
        @inline function _offscatter!(P::Matrix{TG}, n::Int, xo::Int, k1::Int, k2::Int, τ::TG, offp::Vector{Int}, offi::Vector{Int}, offx::Vector{T}, ::Val{$C}) where {T, TG}
            @inbounds begin
                @nexprs $C c -> (o_c = xo + (c - 1) * n)
                for col in k1:k2
                    @nexprs $C c -> (x_c = τ * P[o_c + col])
                    # a plain multiply–subtract (not a fused muladd), to match `_ldiv_same!`
                    @simd ivdep for p in offp[col]:(offp[col + 1] - 1)
                        i = offi[p]
                        a = offx[p]
                        @nexprs $C c -> (P[o_c + i] -= a * x_c)
                    end
                end
            end
            return nothing
        end

        # P[iperm[i], channels] -= τ·J[i,col]·X[col, channels] — the multi-channel residual, permuted
        @inline function _spmm_sub_perm!(P::Matrix{TG}, n::Int, xo::Int, X::Matrix{TG}, colptr::Vector{Int}, rowval::Vector{Int}, nzval::Vector{T}, iperm::Vector{Int}, τ::TG, ::Val{$C}) where {T, TG}
            j0 = xo ÷ n
            @inbounds begin
                @nexprs $C c -> (o_c = xo + (c - 1) * n)
                for col in 1:n
                    @nexprs $C c -> (x_c = τ * X[col, j0 + c])
                    for p in colptr[col]:(colptr[col + 1] - 1)
                        i = iperm[rowval[p]]
                        a = nzval[p]
                        @nexprs $C c -> (P[o_c + i] = muladd(-a, x_c, P[o_c + i]))
                    end
                end
            end
            return nothing
        end
    end
end

@inline function _offscatter_all!(P::Matrix{TG}, n::Int, m::Int, k1::Int, k2::Int, τ::TG, offp::Vector{Int}, offi::Vector{Int}, offx::Vector{T}) where {T, TG}
    j = 0
    while j + 4 <= m
        _offscatter!(P, n, j * n, k1, k2, τ, offp, offi, offx, Val(4))
        j += 4
    end
    if m - j >= 2
        _offscatter!(P, n, j * n, k1, k2, τ, offp, offi, offx, Val(2))
        j += 2
    end
    m - j == 1 && _offscatter!(P, n, j * n, k1, k2, τ, offp, offi, offx, Val(1))
    return nothing
end

# Block k's kernel on the C channels at P[xo + (c-1)*n + k1 .. k2], then its off-diagonal scatter.
@inline function _block_solve_group!(F::SparseLHLFactorization{T, TG}, k::Int, P::Matrix{TG}, n::Int, xo::Int, W::Vector{TG}, ::Val{C}) where {T, TG, C}
    sym = F.sym
    k1 = sym.R[k]
    k2 = sym.R[k + 1] - 1
    kd = sym.kind[k]
    @inbounds if kd == KIND_SCALAR
        s = F.sinv[sym.kidx[k]]
        for c in 1:C
            P[xo + (c - 1) * n + k1] *= s
        end
    elseif kd == KIND_SMALL
        i = sym.kidx[k]
        _sbm_dispatch!(F.vstore, sym.voff[i], F.gstore, sym.goff[i], k2 - k1 + 1, F.istore, sym.ioff[i], F.swap, sym.soff[i], W, P, xo + k1 - 1, n, Val(C))
    else # KIND_BIG (LU handled in the driver, all m at once)
        g = sym.kidx[k]
        _bigm_solve!(F.lhsh[g], F.ws[g], W, P, xo + k1 - 1, n, Val(C))
    end
    if k > 1 && sym.offp[k2 + 1] > sym.offp[k1]
        _offscatter!(P, n, xo, k1, k2, F.τ, sym.offp, sym.offi, F.offx, Val(C))
    end
    return nothing
end

# The m ≥ 2 channels (first m columns of P, permuted order) solved in place.
function _ldiv_multi_perm!(P::Matrix{TG}, F::SparseLHLFactorization{T, TG}, m::Int) where {T, TG}
    sym = F.sym
    n = sym.n
    W = F.mwork
    @inbounds for k in sym.nblocks:-1:1
        if sym.kind[k] == KIND_LU
            k1 = sym.R[k]
            k2 = sym.R[k + 1] - 1
            PureKLU.solve!(F.lu[sym.kidx[k]], view(P, k1:k2, 1:m); check = false)
            if k > 1 && sym.offp[k2 + 1] > sym.offp[k1]
                _offscatter_all!(P, n, m, k1, k2, F.τ, sym.offp, sym.offi, F.offx)
            end
            continue
        end
        j = 0
        while j + 4 <= m
            _block_solve_group!(F, k, P, n, j * n, W, Val(4))
            j += 4
        end
        if m - j >= 2
            _block_solve_group!(F, k, P, n, j * n, W, Val(2))
            j += 2
        end
        m - j == 1 && _block_solve_group!(F, k, P, n, j * n, W, Val(1))
    end
    return P
end

# B (n × m) ← (σI + τJ)⁻¹ B, a matrix right-hand side of the solve type TG.
function _ldiv_multi!(B::AbstractMatrix{TG}, F::SparseLHLFactorization{T, TG}) where {T, TG}
    F.shifted || throw(ArgumentError("no shift loaded; call slhl_shift! first"))
    sym = F.sym
    n = sym.n
    m = size(B, 2)
    size(B, 1) == n || throw(DimensionMismatch("B has $(size(B, 1)) rows, the factorization is $(n)×$(n)"))
    m == 0 && return B
    m == 1 && return (_ldiv_same!(view(B, :, 1), F); B)
    (sym.nblocks == 1 && B isa Matrix{TG}) && return _ldiv_multi_perm!(B, F, m)  # SCC order is the identity
    P = _grow_scratch!(F, Val(:perm), n, m)
    perm = sym.perm
    @inbounds for j in 1:m, k in 1:n
        P[k, j] = B[perm[k], j]
    end
    _ldiv_multi_perm!(P, F, m)
    @inbounds for j in 1:m, k in 1:n
        B[perm[k], j] = P[k, j]
    end
    return B
end

# A matrix right-hand side of the solve type goes through the multi-channel driver; one of
# another element type is solved column by column (each column through its own channels).
slhl_ldiv!(X::AbstractMatrix{TG}, F::SparseLHLFactorization{T, TG}) where {T, TG} = _ldiv_multi!(X, F)
function slhl_ldiv!(X::AbstractMatrix, F::SparseLHLFactorization)
    for j in axes(X, 2)
        slhl_ldiv!(view(X, :, j), F)
    end
    return X
end
LinearAlgebra.ldiv!(F::SparseLHLFactorization, X::AbstractMatrix) = slhl_ldiv!(X, F)
function LinearAlgebra.ldiv!(Y::AbstractMatrix, F::SparseLHLFactorization, X::AbstractMatrix)
    Y === X || copyto!(Y, X)
    return slhl_ldiv!(Y, F)
end

# The channels of a mixed-element-type right-hand side, split in the permuted order so the
# solve's gather disappears, solved together, merged back.
function _ldiv_channels!(x::AbstractVector{S}, F::SparseLHLFactorization{T, TG}, m::Int) where {S, T, TG}
    F.shifted || throw(ArgumentError("no shift loaded; call slhl_shift! first"))
    sym = F.sym
    n = sym.n
    length(x) == n || throw(DimensionMismatch("x has length $(length(x)), the factorization is $(n)×$(n)"))
    B = _grow_scratch!(F, Val(:solve), n, m)
    if m == 1
        _split_channels!(B, x, S)
        _ldiv_same!(view(B, :, 1), F)
        _merge_channels!(x, B, S)
    elseif sym.nblocks == 1
        _split_channels!(B, x, S)
        _ldiv_multi_perm!(B, F, m)
        _merge_channels!(x, B, S)
    else
        xp = view(x, sym.perm)
        _split_channels!(B, xp, S)
        _ldiv_multi_perm!(B, F, m)
        _merge_channels!(xp, B, S)
    end
    return x
end

# ---- Refinement through channels: the residual of all m channels in one pass over J,
# straight into the permuted scratch, then one multi-channel solve and one update.
function _residual_multi_perm!(P::Matrix{TG}, Bx::Matrix{TG}, Bb::Matrix{TG}, F::SparseLHLFactorization{T, TG}, m::Int) where {T, TG}
    sym = F.sym
    n = sym.n
    perm = sym.perm
    J = F.J
    σ = F.σ
    τ = F.τ
    @inbounds for c in 1:m, k in 1:n
        p = perm[k]
        P[k, c] = muladd(-σ, Bx[p, c], Bb[p, c])
    end
    j = 0
    while j + 4 <= m
        _spmm_sub_perm!(P, n, j * n, Bx, J.colptr, J.rowval, J.nzval, sym.iperm, τ, Val(4))
        j += 4
    end
    if m - j >= 2
        _spmm_sub_perm!(P, n, j * n, Bx, J.colptr, J.rowval, J.nzval, sym.iperm, τ, Val(2))
        j += 2
    end
    m - j == 1 && _spmm_sub_perm!(P, n, j * n, Bx, J.colptr, J.rowval, J.nzval, sym.iperm, τ, Val(1))
    return P
end

function _refine_multi!(Bx::Matrix{TG}, Bb::Matrix{TG}, F::SparseLHLFactorization{T, TG}, m::Int, steps::Int) where {T, TG}
    sym = F.sym
    n = sym.n
    perm = sym.perm
    P = _grow_scratch!(F, Val(:perm), n, m)
    for _ in 1:steps
        _residual_multi_perm!(P, Bx, Bb, F, m)
        _ldiv_multi_perm!(P, F, m)
        @inbounds for c in 1:m, k in 1:n
            Bx[perm[k], c] += P[k, c]
        end
    end
    return Bx
end
