name = "LHLFactorization"
uuid = "2faa5264-e118-4071-8864-e10559f68c7c"
authors = ["SciML"]
version = "2.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

[extensions]
LHLFactorizationPolyesterExt = "Polyester"

[compat]
LinearAlgebra = "1.10"
PrecompileTools = "1.2"
Polyester = "0.7"
Random = "1"
SafeTestsets = "0.1"
SciMLTesting = "2.4"
Test = "1"
julia = "1.10"

[extras]
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLTesting = "09d9d899-5365-40a9-917a-5f67fddea283"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "SafeTestsets", "SciMLTesting", "Polyester"]
